### ISSUE TITLE
MARI: jaws: positions defined incorrectly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3935]
Observed when setting up jaws during MARI migration, on the physical hardware on MARI.

As far as I can tell, the sequence of events is:
- Start galil IOC
- Initially the galil will read the raw position as zero (so the "actual" position is the offset)
- The jaws DB records "get" the current positions
- Some time later, the galil ioc manages to actually read the raw position
- The jaws DB records re-apply the first position they got, resulting in the jaws moving until actual position == offset

This ticket is required for MARI to be able to use their jaws under IBEX.

**Comment by John-Holt-Tessella** [comment]
Is this related to #3201 but for non-zeros?

**Comment by John-Holt-Tessella** [comment]
What other instruments should we do this on. Is it any instrument which has jaws connected to a galil?

**Comment by Tom-Willemsen** [comment]
Sorry, I didn't elaborate enough in my previous comment.
- The reason why this failed on MARI was that MARI's galil is broken and won't send us asynchronous data records. @FreddieAkeroyd says this is a known problem that we don't have a solution for yet
- This caused MARI's galil to read "zero" for a while as it was starting up. After 10 seconds it gave up and fell back to synchronous polling
- In effect, the immediate issue on MARI is fixed by getting the driver to start up in synchronous mode in the first place, which means that it never reads "zero"
- There is still an underlying issue here (hence this ticket going back into the backlog) that the propagation of values to/from the jaws is not always correct - but since it's no longer a blocker for MARI migration I don't think it's necessarily still urgent.

I will document the above problem on the wiki

The suggested implementation for this ticket is to change the definition of "axis ready" in the galil driver from "channel access has started" to "channel access has started and a valid data record has been received".

**Comment by FreddieAkeroyd** [comment]
We have a "known issue" when galils will suddenly stop sending UDP data packets, it looks like MARI is in this state. Only known way to fix it is to power cycle the galil, it could have been like this for a long time as LabVIEW didn't use the UDP data record. There is still an issue that if a valid motor position cannot be obtained for a while on startup then it causes strange jaws behaviour.

**Comment by Tom-Willemsen** [comment]
POLARIS have also hit this issue (and raised a footprints about it)

**Comment by KathrynBaker** [comment]
Same issue seen on ZOOM

**Comment by FreddieAkeroyd** [comment]
There are some SYNC calcouts in the slits DB that sync SP from motor back to the top, I'm not sure of it is these or the INIT that causes the issue. The transform record has IVLA that specify what to do if an input is in alarm, similarly a calcout has IOVA to say what to do if the output is invalid (maybe because one of the input propagates an alarm?). So I wonder if by propagating alarms in the records better we can cause them not to do anything if their inputs are in alarm.

**Comment by John-Holt-Tessella** [comment]
I thought we had decided that we were going to edit the motor record/galil driver so that if the motor had not got its first position it would not accept a new position that was queued? Thereby fixing all motor extentions which sit on top of the galils. Can we right down opurt decision on this ticket my brain has stopped remembering our decision.

**Comment by John-Holt-Tessella** [comment]
Check that this isn't solved in the new galil driver. If so transfer this in.

**Comment by Tom-Willemsen** [comment]
There is a merge to be done between our version and the very newest version of the galil driver - talk to @FreddieAkeroyd before picking up this ticket.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - consider & propose a workaround.  Then think about a longer term solution.

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd have you had a chance to consider workarounds (per comment above)?

**Comment by John-Holt-Tessella** [comment]
Set all motors on Crisp to DR (added ve loop pole time). The difference in resource manager is small:

@-20 (except 4)
![image](https://user-images.githubusercontent.com/7570055/57538391-3a04b900-7340-11e9-89a3-6ed667051dad.png)

@20 (except 4)

![image](https://user-images.githubusercontent.com/7570055/57538418-47ba3e80-7340-11e9-9cfc-2b9bccee2b16.png)

**Comment by John-Holt-Tessella** [comment]
/remind @Kevin-Woods-Tessella 11th June 2019 Ticket 3935

**Comment by John-Holt-Tessella** [comment]
\remind @Kevin-Woods-Tessella 11th July 2019 Ticket 3935
